### ISSUE TITLE
Client with Merchants connecting with Server without Error readout.

### ISSUE THREAD

**Issue by Bunsan** [Aleksey-Terzi/MerchantsTFC#6]
We have found that if a client has merchants in their instance and the server they are connecting to does not they just get a connection Error. There is no error message indicating that the client has a mod the server does not and so the user would be challenged to determine why they could not connect.

**Comment by Aleksey-Terzi** [comment]
Ok, thank you for bug report.
One more person declared this problem.
Asked for details on TFC forum.
